<h1 align="center">Hi! I'm Shofi! 👋🏻</h1>

###

<div align="center">
  <img src="https://github-readme-stats.vercel.app/api/top-langs?username=shoffice&locale=en&hide_title=true&layout=compact&card_width=320&langs_count=7&theme=rose_pine&hide_border=true" height="200" alt="languages graph"  />
</div>

###

<br clear="both">

<div align="center">
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg" height="50" alt="c logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg" height="50" alt="cplusplus logo"  />
  <img width="12" />
  <img src="https://skillicons.dev/icons?i=html" height="50" alt="html5 logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" height="50" alt="css3 logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" height="50" alt="javascript logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg" height="50" alt="mysql logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg" height="50" alt="java logo"  />
  <img width="12" />
  <img src="https://skillicons.dev/icons?i=php" height="50" alt="php logo"  />
  <img width="12" />
  <img src="https://cdn.simpleicons.org/androidstudio/3DDC84" height="50" alt="androidstudio logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg" height="50" alt="python logo"  />
</div>

###

<img src="https://raw.githubusercontent.com/shoffice/shoffice/output/snake.svg" alt="Snake animation" />

###

<img align="left" height="200" src="https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExOHlqcHByNGN1bjVqbTRmdzgxMnE4NmEzaDBrejgzZjI4cmR0aTVleiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/qd641DVFl2CLC/giphy.gif"  />

###

<div align="center">
  <a href="https://instagram.com/shofiyass" target="_blank">
    <img src="https://raw.githubusercontent.com/maurodesouza/profile-readme-generator/master/src/assets/icons/social/instagram/default.svg" width="61" height="45" alt="instagram logo"  />
  </a>
  <a href="https://www.linkedin.com/in/shofiya-yasmin-husna-a6b37224b/" target="_blank">
    <img src="https://raw.githubusercontent.com/maurodesouza/profile-readme-generator/master/src/assets/icons/social/linkedin/default.svg" width="61" height="45" alt="linkedin logo"  />
  </a>
  <a href="https://www.youtube.com/@shofiyasminh" target="_blank">
    <img src="https://raw.githubusercontent.com/maurodesouza/profile-readme-generator/master/src/assets/icons/social/youtube/default.svg" width="61" height="45" alt="youtube logo"  />
  </a>
</div>

###
